# Generated by Django 5.2 on 2026-05-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disquera', '0004_cartitem_user_alter_category_color_hex_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='songs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
