# Generated by Django 5.2 on 2026-05-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disquera', '0005_post_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
