# Generated by Django 5.2 on 2026-05-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disquera', '0006_profile_bio_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='disquera.category'),
        ),
    ]
